# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/xdma_u280_official.xci
# IP: The module: 'xdma_u280_official' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_2/xdma_v4_1_23_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_23_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_23_blk_mem_64_noreg_be} -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_1/xdma_v4_1_23_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_23_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_23_blk_mem_64_reg_be} -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/xdma_u280_official_pcie4c_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/ip_0/xdma_u280_official_pcie4c_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip_gt || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip_gt} -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_2/xdma_v4_1_23_blk_mem_64_noreg_be_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_1/xdma_v4_1_23_blk_mem_64_reg_be_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/ip_0/synth/xdma_u280_official_pcie4c_ip_gt_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/ip_0/synth/xdma_u280_official_pcie4c_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip_gt || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/xdma_u280_official_pcie4c_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/source/ip_pcie4c_uscale_plus_impl_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/synth/xdma_u280_official_pcie4c_ip_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/synth/xdma_u280_official_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/source/ip_pcie4c_uscale_plus_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/xdma_u280_official_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_u280_official'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/source/xdma_u280_official_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_u280_official'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/synth/xdma_u280_official_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_u280_official'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/xdma_u280_official.xci
# IP: The module: 'xdma_u280_official' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_2/xdma_v4_1_23_blk_mem_64_noreg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_23_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_23_blk_mem_64_noreg_be} -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_1/xdma_v4_1_23_blk_mem_64_reg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_23_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_23_blk_mem_64_reg_be} -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/xdma_u280_official_pcie4c_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] -quiet

# IP: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/ip_0/xdma_u280_official_pcie4c_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip_gt || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip_gt} -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_2/xdma_v4_1_23_blk_mem_64_noreg_be_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_1/xdma_v4_1_23_blk_mem_64_reg_be_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/ip_0/synth/xdma_u280_official_pcie4c_ip_gt_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/ip_0/synth/xdma_u280_official_pcie4c_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip_gt || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/xdma_u280_official_pcie4c_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/source/ip_pcie4c_uscale_plus_impl_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/synth/xdma_u280_official_pcie4c_ip_ooc.xdc

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/synth/xdma_u280_official_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/ip_0/source/ip_pcie4c_uscale_plus_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_u280_official_pcie4c_ip || ORIG_REF_NAME==xdma_u280_official_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/xdma_u280_official_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_u280_official'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/source/xdma_u280_official_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_u280_official'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/vivado_ex/xdma_u280_official_ex/xdma_u280_official_ex.srcs/sources_1/ip/xdma_u280_official/synth/xdma_u280_official_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_u280_official'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
